// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shelduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// tasks status
type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_DRAFT       TaskStatus = 1
	TaskStatus_TASK_STATUS_QUEUED      TaskStatus = 2
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 3
	TaskStatus_TASK_STATUS_SUCCESS     TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 5
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 6
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_DRAFT",
		2: "TASK_STATUS_QUEUED",
		3: "TASK_STATUS_RUNNING",
		4: "TASK_STATUS_SUCCESS",
		5: "TASK_STATUS_FAILED",
		6: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_DRAFT":       1,
		"TASK_STATUS_QUEUED":      2,
		"TASK_STATUS_RUNNING":     3,
		"TASK_STATUS_SUCCESS":     4,
		"TASK_STATUS_FAILED":      5,
		"TASK_STATUS_CANCELLED":   6,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shelduler_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_shelduler_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{0}
}

// attempt status
type AttemptStatus int32

const (
	AttemptStatus_ATTEMPT_STATUS_UNSPECIFIED AttemptStatus = 0
	AttemptStatus_ATTEMPT_STATUS_STARTED     AttemptStatus = 1
	AttemptStatus_ATTEMPT_STATUS_SUCCESS     AttemptStatus = 2
	AttemptStatus_ATTEMPT_STATUS_FAILED      AttemptStatus = 3
)

// Enum value maps for AttemptStatus.
var (
	AttemptStatus_name = map[int32]string{
		0: "ATTEMPT_STATUS_UNSPECIFIED",
		1: "ATTEMPT_STATUS_STARTED",
		2: "ATTEMPT_STATUS_SUCCESS",
		3: "ATTEMPT_STATUS_FAILED",
	}
	AttemptStatus_value = map[string]int32{
		"ATTEMPT_STATUS_UNSPECIFIED": 0,
		"ATTEMPT_STATUS_STARTED":     1,
		"ATTEMPT_STATUS_SUCCESS":     2,
		"ATTEMPT_STATUS_FAILED":      3,
	}
)

func (x AttemptStatus) Enum() *AttemptStatus {
	p := new(AttemptStatus)
	*p = x
	return p
}

func (x AttemptStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttemptStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shelduler_proto_enumTypes[1].Descriptor()
}

func (AttemptStatus) Type() protoreflect.EnumType {
	return &file_shelduler_proto_enumTypes[1]
}

func (x AttemptStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttemptStatus.Descriptor instead.
func (AttemptStatus) EnumDescriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{1}
}

// task
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=scheduler.v1.TaskStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Requirements  *TaskRequirements      `protobuf:"bytes,10,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Priority      int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	WorkerId      string                 `protobuf:"bytes,12,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_shelduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Task) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Task) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Task) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Task) GetRequirements() *TaskRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// schedule
type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cron          string                 `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_shelduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{1}
}

func (x *Schedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schedule) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *Schedule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Schedule) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Schedule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// attempt
type Attempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Status        AttemptStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=scheduler.v1.AttemptStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_shelduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attempt.ProtoReflect.Descriptor instead.
func (*Attempt) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{2}
}

func (x *Attempt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attempt) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Attempt) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Attempt) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Attempt) GetStatus() AttemptStatus {
	if x != nil {
		return x.Status
	}
	return AttemptStatus_ATTEMPT_STATUS_UNSPECIFIED
}

func (x *Attempt) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// create task request and response
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Requirements  *TaskRequirements      `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	WorkerId      string                 `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_shelduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateTaskRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CreateTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateTaskRequest) GetRequirements() *TaskRequirements {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_shelduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// get task request and response
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_shelduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_shelduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// list tasks request and response
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=scheduler.v1.TaskStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_shelduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_shelduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// cancel task request and response
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_shelduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelTaskRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_shelduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// update task status request and response
type UpdateTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=scheduler.v1.TaskStatus" json:"status,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusRequest) Reset() {
	*x = UpdateTaskStatusRequest{}
	mi := &file_shelduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusRequest) ProtoMessage() {}

func (x *UpdateTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateTaskStatusRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskStatusResponse) Reset() {
	*x = UpdateTaskStatusResponse{}
	mi := &file_shelduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskStatusResponse) ProtoMessage() {}

func (x *UpdateTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTaskStatusResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// create schedule request and response
type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cron          string                 `protobuf:"bytes,1,opt,name=cron,proto3" json:"cron,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_shelduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{13}
}

func (x *CreateScheduleRequest) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CreateScheduleRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateScheduleRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateScheduleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_shelduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{14}
}

func (x *CreateScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

// list schedules request and response
type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_shelduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{15}
}

func (x *ListSchedulesRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ListSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSchedulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_shelduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{16}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// report attempt request and response
type ReportAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        AttemptStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=scheduler.v1.AttemptStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAttemptRequest) Reset() {
	*x = ReportAttemptRequest{}
	mi := &file_shelduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttemptRequest) ProtoMessage() {}

func (x *ReportAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttemptRequest.ProtoReflect.Descriptor instead.
func (*ReportAttemptRequest) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{17}
}

func (x *ReportAttemptRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportAttemptRequest) GetStatus() AttemptStatus {
	if x != nil {
		return x.Status
	}
	return AttemptStatus_ATTEMPT_STATUS_UNSPECIFIED
}

func (x *ReportAttemptRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReportAttemptRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReportAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *Attempt               `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAttemptResponse) Reset() {
	*x = ReportAttemptResponse{}
	mi := &file_shelduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAttemptResponse) ProtoMessage() {}

func (x *ReportAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAttemptResponse.ProtoReflect.Descriptor instead.
func (*ReportAttemptResponse) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{18}
}

func (x *ReportAttemptResponse) GetAttempt() *Attempt {
	if x != nil {
		return x.Attempt
	}
	return nil
}

type TaskRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`       // capability tags required
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`   // preferred/required region
	Cpu           float64                `protobuf:"fixed64,3,opt,name=cpu,proto3" json:"cpu,omitempty"`       // requested vCPU units
	Memory        float64                `protobuf:"fixed64,4,opt,name=memory,proto3" json:"memory,omitempty"` // requested memory in MB
	RequiresGpu   bool                   `protobuf:"varint,5,opt,name=requires_gpu,json=requiresGpu,proto3" json:"requires_gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequirements) Reset() {
	*x = TaskRequirements{}
	mi := &file_shelduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequirements) ProtoMessage() {}

func (x *TaskRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_shelduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequirements.ProtoReflect.Descriptor instead.
func (*TaskRequirements) Descriptor() ([]byte, []int) {
	return file_shelduler_proto_rawDescGZIP(), []int{19}
}

func (x *TaskRequirements) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TaskRequirements) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *TaskRequirements) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *TaskRequirements) GetMemory() float64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *TaskRequirements) GetRequiresGpu() bool {
	if x != nil {
		return x.RequiresGpu
	}
	return false
}

var File_shelduler_proto protoreflect.FileDescriptor

const file_shelduler_proto_rawDesc = "" +
	"\n" +
	"\x0fshelduler.proto\x12\fscheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.scheduler.v1.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fscheduled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12B\n" +
	"\frequirements\x18\n" +
	" \x01(\v2\x1e.scheduler.v1.TaskRequirementsR\frequirements\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12\x1b\n" +
	"\tworker_id\x18\f \x01(\tR\bworkerId\"\x9d\x01\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cron\x18\x02 \x01(\tR\x04cron\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf5\x01\n" +
	"\aAttempt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.scheduler.v1.AttemptStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\x88\x02\n" +
	"\x11CreateTaskRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12=\n" +
	"\fscheduled_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12B\n" +
	"\frequirements\x18\x04 \x01(\v2\x1e.scheduler.v1.TaskRequirementsR\frequirements\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\"<\n" +
	"\x12CreateTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.scheduler.v1.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.scheduler.v1.TaskR\x04task\"r\n" +
	"\x10ListTasksRequest\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.scheduler.v1.TaskStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"S\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.scheduler.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"B\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"<\n" +
	"\x12CancelTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.scheduler.v1.TaskR\x04task\"\x99\x01\n" +
	"\x17UpdateTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.scheduler.v1.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"B\n" +
	"\x18UpdateTaskStatusResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.scheduler.v1.TaskR\x04task\"~\n" +
	"\x15CreateScheduleRequest\x12\x12\n" +
	"\x04cron\x18\x01 \x01(\tR\x04cron\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"L\n" +
	"\x16CreateScheduleResponse\x122\n" +
	"\bschedule\x18\x01 \x01(\v2\x16.scheduler.v1.ScheduleR\bschedule\"^\n" +
	"\x14ListSchedulesRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"c\n" +
	"\x15ListSchedulesResponse\x124\n" +
	"\tschedules\x18\x01 \x03(\v2\x16.scheduler.v1.ScheduleR\tschedules\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x99\x01\n" +
	"\x14ReportAttemptRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.scheduler.v1.AttemptStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"H\n" +
	"\x15ReportAttemptResponse\x12/\n" +
	"\aattempt\x18\x01 \x01(\v2\x15.scheduler.v1.AttemptR\aattempt\"\x8b\x01\n" +
	"\x10TaskRequirements\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\x01R\x06memory\x12!\n" +
	"\frequires_gpu\x18\x05 \x01(\bR\vrequiresGpu*\xbd\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_STATUS_DRAFT\x10\x01\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x02\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x03\x12\x17\n" +
	"\x13TASK_STATUS_SUCCESS\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x06*\x82\x01\n" +
	"\rAttemptStatus\x12\x1e\n" +
	"\x1aATTEMPT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ATTEMPT_STATUS_STARTED\x10\x01\x12\x1a\n" +
	"\x16ATTEMPT_STATUS_SUCCESS\x10\x02\x12\x19\n" +
	"\x15ATTEMPT_STATUS_FAILED\x10\x032\xbe\x05\n" +
	"\x10SchedulerService\x12O\n" +
	"\n" +
	"CreateTask\x12\x1f.scheduler.v1.CreateTaskRequest\x1a .scheduler.v1.CreateTaskResponse\x12F\n" +
	"\aGetTask\x12\x1c.scheduler.v1.GetTaskRequest\x1a\x1d.scheduler.v1.GetTaskResponse\x12L\n" +
	"\tListTasks\x12\x1e.scheduler.v1.ListTasksRequest\x1a\x1f.scheduler.v1.ListTasksResponse\x12O\n" +
	"\n" +
	"CancelTask\x12\x1f.scheduler.v1.CancelTaskRequest\x1a .scheduler.v1.CancelTaskResponse\x12[\n" +
	"\x0eCreateSchedule\x12#.scheduler.v1.CreateScheduleRequest\x1a$.scheduler.v1.CreateScheduleResponse\x12X\n" +
	"\rListSchedules\x12\".scheduler.v1.ListSchedulesRequest\x1a#.scheduler.v1.ListSchedulesResponse\x12a\n" +
	"\x10UpdateTaskStatus\x12%.scheduler.v1.UpdateTaskStatusRequest\x1a&.scheduler.v1.UpdateTaskStatusResponse\x12X\n" +
	"\rReportAttempt\x12\".scheduler.v1.ReportAttemptRequest\x1a#.scheduler.v1.ReportAttemptResponseB)Z'task_shelduler/pkg/proto/v1;schedulerv1b\x06proto3"

var (
	file_shelduler_proto_rawDescOnce sync.Once
	file_shelduler_proto_rawDescData []byte
)

func file_shelduler_proto_rawDescGZIP() []byte {
	file_shelduler_proto_rawDescOnce.Do(func() {
		file_shelduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shelduler_proto_rawDesc), len(file_shelduler_proto_rawDesc)))
	})
	return file_shelduler_proto_rawDescData
}

var file_shelduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shelduler_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_shelduler_proto_goTypes = []any{
	(TaskStatus)(0),                  // 0: scheduler.v1.TaskStatus
	(AttemptStatus)(0),               // 1: scheduler.v1.AttemptStatus
	(*Task)(nil),                     // 2: scheduler.v1.Task
	(*Schedule)(nil),                 // 3: scheduler.v1.Schedule
	(*Attempt)(nil),                  // 4: scheduler.v1.Attempt
	(*CreateTaskRequest)(nil),        // 5: scheduler.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),       // 6: scheduler.v1.CreateTaskResponse
	(*GetTaskRequest)(nil),           // 7: scheduler.v1.GetTaskRequest
	(*GetTaskResponse)(nil),          // 8: scheduler.v1.GetTaskResponse
	(*ListTasksRequest)(nil),         // 9: scheduler.v1.ListTasksRequest
	(*ListTasksResponse)(nil),        // 10: scheduler.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),        // 11: scheduler.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),       // 12: scheduler.v1.CancelTaskResponse
	(*UpdateTaskStatusRequest)(nil),  // 13: scheduler.v1.UpdateTaskStatusRequest
	(*UpdateTaskStatusResponse)(nil), // 14: scheduler.v1.UpdateTaskStatusResponse
	(*CreateScheduleRequest)(nil),    // 15: scheduler.v1.CreateScheduleRequest
	(*CreateScheduleResponse)(nil),   // 16: scheduler.v1.CreateScheduleResponse
	(*ListSchedulesRequest)(nil),     // 17: scheduler.v1.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),    // 18: scheduler.v1.ListSchedulesResponse
	(*ReportAttemptRequest)(nil),     // 19: scheduler.v1.ReportAttemptRequest
	(*ReportAttemptResponse)(nil),    // 20: scheduler.v1.ReportAttemptResponse
	(*TaskRequirements)(nil),         // 21: scheduler.v1.TaskRequirements
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
}
var file_shelduler_proto_depIdxs = []int32{
	0,  // 0: scheduler.v1.Task.status:type_name -> scheduler.v1.TaskStatus
	22, // 1: scheduler.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: scheduler.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	22, // 3: scheduler.v1.Task.scheduled_at:type_name -> google.protobuf.Timestamp
	21, // 4: scheduler.v1.Task.requirements:type_name -> scheduler.v1.TaskRequirements
	22, // 5: scheduler.v1.Schedule.created_at:type_name -> google.protobuf.Timestamp
	22, // 6: scheduler.v1.Attempt.started_at:type_name -> google.protobuf.Timestamp
	22, // 7: scheduler.v1.Attempt.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 8: scheduler.v1.Attempt.status:type_name -> scheduler.v1.AttemptStatus
	22, // 9: scheduler.v1.CreateTaskRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	21, // 10: scheduler.v1.CreateTaskRequest.requirements:type_name -> scheduler.v1.TaskRequirements
	2,  // 11: scheduler.v1.CreateTaskResponse.task:type_name -> scheduler.v1.Task
	2,  // 12: scheduler.v1.GetTaskResponse.task:type_name -> scheduler.v1.Task
	0,  // 13: scheduler.v1.ListTasksRequest.status:type_name -> scheduler.v1.TaskStatus
	2,  // 14: scheduler.v1.ListTasksResponse.tasks:type_name -> scheduler.v1.Task
	2,  // 15: scheduler.v1.CancelTaskResponse.task:type_name -> scheduler.v1.Task
	0,  // 16: scheduler.v1.UpdateTaskStatusRequest.status:type_name -> scheduler.v1.TaskStatus
	2,  // 17: scheduler.v1.UpdateTaskStatusResponse.task:type_name -> scheduler.v1.Task
	3,  // 18: scheduler.v1.CreateScheduleResponse.schedule:type_name -> scheduler.v1.Schedule
	3,  // 19: scheduler.v1.ListSchedulesResponse.schedules:type_name -> scheduler.v1.Schedule
	1,  // 20: scheduler.v1.ReportAttemptRequest.status:type_name -> scheduler.v1.AttemptStatus
	4,  // 21: scheduler.v1.ReportAttemptResponse.attempt:type_name -> scheduler.v1.Attempt
	5,  // 22: scheduler.v1.SchedulerService.CreateTask:input_type -> scheduler.v1.CreateTaskRequest
	7,  // 23: scheduler.v1.SchedulerService.GetTask:input_type -> scheduler.v1.GetTaskRequest
	9,  // 24: scheduler.v1.SchedulerService.ListTasks:input_type -> scheduler.v1.ListTasksRequest
	11, // 25: scheduler.v1.SchedulerService.CancelTask:input_type -> scheduler.v1.CancelTaskRequest
	15, // 26: scheduler.v1.SchedulerService.CreateSchedule:input_type -> scheduler.v1.CreateScheduleRequest
	17, // 27: scheduler.v1.SchedulerService.ListSchedules:input_type -> scheduler.v1.ListSchedulesRequest
	13, // 28: scheduler.v1.SchedulerService.UpdateTaskStatus:input_type -> scheduler.v1.UpdateTaskStatusRequest
	19, // 29: scheduler.v1.SchedulerService.ReportAttempt:input_type -> scheduler.v1.ReportAttemptRequest
	6,  // 30: scheduler.v1.SchedulerService.CreateTask:output_type -> scheduler.v1.CreateTaskResponse
	8,  // 31: scheduler.v1.SchedulerService.GetTask:output_type -> scheduler.v1.GetTaskResponse
	10, // 32: scheduler.v1.SchedulerService.ListTasks:output_type -> scheduler.v1.ListTasksResponse
	12, // 33: scheduler.v1.SchedulerService.CancelTask:output_type -> scheduler.v1.CancelTaskResponse
	16, // 34: scheduler.v1.SchedulerService.CreateSchedule:output_type -> scheduler.v1.CreateScheduleResponse
	18, // 35: scheduler.v1.SchedulerService.ListSchedules:output_type -> scheduler.v1.ListSchedulesResponse
	14, // 36: scheduler.v1.SchedulerService.UpdateTaskStatus:output_type -> scheduler.v1.UpdateTaskStatusResponse
	20, // 37: scheduler.v1.SchedulerService.ReportAttempt:output_type -> scheduler.v1.ReportAttemptResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_shelduler_proto_init() }
func file_shelduler_proto_init() {
	if File_shelduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shelduler_proto_rawDesc), len(file_shelduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shelduler_proto_goTypes,
		DependencyIndexes: file_shelduler_proto_depIdxs,
		EnumInfos:         file_shelduler_proto_enumTypes,
		MessageInfos:      file_shelduler_proto_msgTypes,
	}.Build()
	File_shelduler_proto = out.File
	file_shelduler_proto_goTypes = nil
	file_shelduler_proto_depIdxs = nil
}
